"""fix unique constraints with filtered indexes

Revision ID: 2c0fc9c02228
Revises: 
Create Date: 2025-09-26 14:26:38.425472

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c0fc9c02228'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Student_Identity', sa.Integer(), nullable=True),
    sa.Column('Teacher_Identity', sa.Integer(), nullable=True),
    sa.Column('Management_Admin_Identity', sa.Integer(), nullable=True),
    sa.Column('Schedule', sa.String(length=80), nullable=True),
    sa.Column('Major', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('roles',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Role_Name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_Name', sa.String(length=80), nullable=False),
    sa.Column('User_Email', sa.String(length=100), nullable=False),
    sa.Column('FK_Rol_ID', sa.Integer(), nullable=False),
    sa.Column('Telephone', sa.BigInteger(), nullable=False),
    sa.Column('FK_Identity_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FK_Identity_ID'], ['identities.Id'], ),
    sa.ForeignKeyConstraint(['FK_Rol_ID'], ['roles.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('User_Email')
    )
    op.create_table('califications',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FK_User_ID', sa.Integer(), nullable=False),
    sa.Column('Average', sa.Float(), nullable=False),
    sa.Column('IsApproved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['FK_User_ID'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('tokens',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Token', sa.String(length=400), nullable=False),
    sa.Column('InBlackList', sa.Boolean(), nullable=False),
    sa.Column('FK_User_ID', sa.Integer(), nullable=False),
    sa.Column('Date_Expiration_Time', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['FK_User_ID'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('califications')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('identities')
    # ### end Alembic commands ###
