"""init schema v2 with students, users, roles

Revision ID: 4d5a4e1b47eb
Revises: df64cb97cc04
Create Date: 2025-09-24 10:38:17.505823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d5a4e1b47eb'
down_revision: Union[str, Sequence[str], None] = 'df64cb97cc04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Role_Name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('users',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('User_Name', sa.String(length=80), nullable=False),
    sa.Column('User_Email', sa.String(length=100), nullable=False),
    sa.Column('FK_Rol_ID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['FK_Rol_ID'], ['roles.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('User_Email')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
