"""init schema v3 with tokens and califications

Revision ID: 53f52a12e210
Revises: e11f73912b0b
Create Date: 2025-09-24 11:15:21.896374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f52a12e210'
down_revision: Union[str, Sequence[str], None] = 'e11f73912b0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('califications',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('FK_User_ID', sa.Integer(), nullable=False),
    sa.Column('Average', sa.Float(), nullable=False),
    sa.Column('IsApproved', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['FK_User_ID'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('tokens',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Token', sa.String(length=400), nullable=False),
    sa.Column('InBlackList', sa.Boolean(), nullable=False),
    sa.Column('FK_User_ID', sa.Integer(), nullable=False),
    sa.Column('Date_Expiration_Time', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['FK_User_ID'], ['users.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Token')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    op.drop_table('califications')
    # ### end Alembic commands ###
