"""updates v5

Revision ID: 5876a2d5f8cc
Revises: e9a568c497e8
Create Date: 2025-11-30 19:15:52.283602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5876a2d5f8cc'
down_revision: Union[str, Sequence[str], None] = 'e9a568c497e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_card_items', sa.Column('Calificacion1', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('report_card_items', sa.Column('Calificacion2', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('report_card_items', sa.Column('Calificacion3', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('report_card_items', sa.Column('Asistencia1', sa.String(length=16), nullable=True))
    op.add_column('report_card_items', sa.Column('Asistencia2', sa.String(length=16), nullable=True))
    op.add_column('report_card_items', sa.Column('Asistencia3', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_card_items', 'Asistencia3')
    op.drop_column('report_card_items', 'Asistencia2')
    op.drop_column('report_card_items', 'Asistencia1')
    op.drop_column('report_card_items', 'Calificacion3')
    op.drop_column('report_card_items', 'Calificacion2')
    op.drop_column('report_card_items', 'Calificacion1')
    # ### end Alembic commands ###
