"""add identity Grupo column

Revision ID: 6801b9fe5ccb
Revises: a4a1692ed696
Create Date: 2025-12-01 02:46:17.696562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6801b9fe5ccb'
down_revision: Union[str, Sequence[str], None] = 'a4a1692ed696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identities', sa.Column('Grupo', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identities', 'Grupo')
    # ### end Alembic commands ###
