"""init schema v3 without student

Revision ID: 8ee00a22beeb
Revises: 53f52a12e210
Create Date: 2025-09-24 11:16:33.999495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee00a22beeb'
down_revision: Union[str, Sequence[str], None] = '53f52a12e210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.Column('matricula', sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=120, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('PK__students__3213E83F5899C96C'))
    )
    # ### end Alembic commands ###
