"""updates v6

Revision ID: a4a1692ed696
Revises: 5876a2d5f8cc
Create Date: 2025-11-30 19:27:38.395265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4a1692ed696'
down_revision: Union[str, Sequence[str], None] = '5876a2d5f8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_card_items', 'Calificacion1',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('report_card_items', 'Calificacion2',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('report_card_items', 'Calificacion3',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               type_=sa.String(length=16),
               existing_nullable=True)
    op.alter_column('report_card_items', 'Asistencia1',
               existing_type=sa.VARCHAR(length=16, collation='Modern_Spanish_CI_AS'),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('report_card_items', 'Asistencia2',
               existing_type=sa.VARCHAR(length=16, collation='Modern_Spanish_CI_AS'),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('report_card_items', 'Asistencia3',
               existing_type=sa.VARCHAR(length=16, collation='Modern_Spanish_CI_AS'),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('report_card_items', 'Asistencia3',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=16, collation='Modern_Spanish_CI_AS'),
               existing_nullable=True)
    op.alter_column('report_card_items', 'Asistencia2',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=16, collation='Modern_Spanish_CI_AS'),
               existing_nullable=True)
    op.alter_column('report_card_items', 'Asistencia1',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=16, collation='Modern_Spanish_CI_AS'),
               existing_nullable=True)
    op.alter_column('report_card_items', 'Calificacion3',
               existing_type=sa.String(length=16),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('report_card_items', 'Calificacion2',
               existing_type=sa.String(length=16),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    op.alter_column('report_card_items', 'Calificacion1',
               existing_type=sa.String(length=16),
               type_=sa.NUMERIC(precision=4, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
