"""updates

Revision ID: a68a7fd643fd
Revises: e770f4859e42
Create Date: 2025-11-30 17:58:26.204626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a68a7fd643fd'
down_revision: Union[str, Sequence[str], None] = 'e770f4859e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rci_clave'), table_name='report_card_items')
    op.drop_index(op.f('ix_rci_semestre'), table_name='report_card_items')
    # Some deployments may already have removed this FK (name varies by server).
    # Drop it only if it exists to avoid failures when applying migrations.
    op.execute(
        """
IF EXISTS (
    SELECT 1 FROM sys.foreign_keys WHERE name = 'FK__report_ca__UAC_I__17C286CF'
)
BEGIN
    ALTER TABLE report_card_items DROP CONSTRAINT [FK__report_ca__UAC_I__17C286CF]
END
"""
    )
    op.drop_column('report_card_items', 'Tipo_UAC')
    op.drop_column('report_card_items', 'Creditos')
    op.drop_column('report_card_items', 'Horas_Sem')
    # Drop any foreign-key constraints that reference report_card_items.UAC_ID,
    # then drop the column — all guarded by existence checks to make the
    # migration idempotent across heterogeneous environments.
    op.execute(
        """
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('report_card_items') AND name = 'UAC_ID')
BEGIN
    DECLARE @sql NVARCHAR(MAX) = NULL;
    SELECT @sql = STRING_AGG('ALTER TABLE [' + OBJECT_SCHEMA_NAME(fk.parent_object_id) + '].[' + OBJECT_NAME(fk.parent_object_id) + '] DROP CONSTRAINT [' + fk.name + ']', '; ')
    FROM sys.foreign_keys fk
    JOIN sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
    JOIN sys.columns c ON fkc.parent_object_id = c.object_id AND fkc.parent_column_id = c.column_id
    WHERE OBJECT_NAME(fk.parent_object_id) = 'report_card_items' AND c.name = 'UAC_ID';

    IF @sql IS NOT NULL
        EXEC(@sql);

    ALTER TABLE report_card_items DROP COLUMN [UAC_ID];
END
"""
    )
    op.drop_column('report_card_items', 'Periodo_Item')
    op.drop_index(op.f('ix_rcr_identity_periodo_clave'), table_name='report_card_raw')
    op.create_index('ix_rcr_identity_clave', 'report_card_raw', ['Identity_ID', 'Clave_UAC'], unique=False)
    op.drop_column('report_card_raw', 'Periodo')
    op.drop_column('report_card_raw', 'Periodo_Item')
    op.drop_column('report_card_raw', 'Stored_URI')
    op.drop_column('uacs', 'Horas_Sem')
    op.drop_column('uacs', 'Creditos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uacs', sa.Column('Creditos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('uacs', sa.Column('Horas_Sem', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('report_card_raw', sa.Column('Stored_URI', sa.VARCHAR(length=400, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('report_card_raw', sa.Column('Periodo_Item', sa.VARCHAR(length=64, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('report_card_raw', sa.Column('Periodo', sa.VARCHAR(length=64, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=False))
    op.drop_index('ix_rcr_identity_clave', table_name='report_card_raw')
    op.create_index(op.f('ix_rcr_identity_periodo_clave'), 'report_card_raw', ['Identity_ID', 'Periodo', 'Clave_UAC'], unique=False)
    op.add_column('report_card_items', sa.Column('Periodo_Item', sa.VARCHAR(length=64, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.add_column('report_card_items', sa.Column('UAC_ID', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('report_card_items', sa.Column('Horas_Sem', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('report_card_items', sa.Column('Creditos', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('report_card_items', sa.Column('Tipo_UAC', sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('FK__report_ca__UAC_I__17C286CF'), 'report_card_items', 'uacs', ['UAC_ID'], ['Id'])
    op.create_index(op.f('ix_rci_semestre'), 'report_card_items', ['Semestre'], unique=False)
    op.create_index(op.f('ix_rci_clave'), 'report_card_items', ['Clave_UAC'], unique=False)
    # ### end Alembic commands ###
