"""MIGRACIONES FOR REPORT CARDS

Revision ID: a8a8c0ae0e3e
Revises: 7488558f8abc
Create Date: 2025-10-23 22:49:23.323327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a8c0ae0e3e'
down_revision: Union[str, Sequence[str], None] = '7488558f8abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uacs',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Clave', sa.String(length=32), nullable=False),
    sa.Column('Nombre', sa.String(length=200), nullable=False),
    sa.Column('Tipo', sa.String(length=32), nullable=True),
    sa.Column('Creditos', sa.Integer(), nullable=True),
    sa.Column('Horas_Sem', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Clave')
    )
    op.create_table('report_card_raw',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Identity_ID', sa.Integer(), nullable=False),
    sa.Column('Periodo', sa.String(length=64), nullable=False),
    sa.Column('Raw_JSON', sa.Text(), nullable=False),
    sa.Column('SHA256', sa.String(length=64), nullable=False),
    sa.Column('Stored_URI', sa.String(length=400), nullable=True),
    sa.Column('Created_At', sa.DateTime(timezone=True), server_default=sa.text('sysdatetime()'), nullable=False),
    sa.ForeignKeyConstraint(['Identity_ID'], ['identities.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('SHA256', name='uq_rcr_sha256')
    )
    op.create_table('report_cards',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Identity_ID', sa.Integer(), nullable=False),
    sa.Column('Periodo', sa.String(length=64), nullable=False),
    sa.Column('Plan_Estudios', sa.String(length=120), nullable=True),
    sa.Column('Carrera', sa.String(length=150), nullable=True),
    sa.Column('Avance_Oblig', sa.Integer(), nullable=False),
    sa.Column('Avance_Opt', sa.Integer(), nullable=False),
    sa.Column('Avance_Total', sa.Integer(), nullable=False),
    sa.Column('Promedio', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('Src_SHA256', sa.String(length=64), nullable=True),
    sa.Column('Created_At', sa.DateTime(timezone=True), server_default=sa.text('sysdatetime()'), nullable=False),
    sa.Column('Updated_At', sa.DateTime(timezone=True), server_default=sa.text('sysdatetime()'), nullable=True),
    sa.ForeignKeyConstraint(['Identity_ID'], ['identities.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Identity_ID', 'Periodo', name='uq_report_cards_identity_periodo')
    )
    op.create_index('ix_report_cards_identity_periodo', 'report_cards', ['Identity_ID', 'Periodo'], unique=False)
    op.create_index('ix_report_cards_periodo', 'report_cards', ['Periodo'], unique=False)
    op.create_table('report_card_items',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ReportCard_ID', sa.Integer(), nullable=False),
    sa.Column('UAC_ID', sa.Integer(), nullable=True),
    sa.Column('Clave_UAC', sa.String(length=32), nullable=False),
    sa.Column('Semestre', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=200), nullable=False),
    sa.Column('Tipo_UAC', sa.String(length=32), nullable=True),
    sa.Column('Calificacion', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('Horas_Sem', sa.Integer(), nullable=True),
    sa.Column('Creditos', sa.Integer(), nullable=True),
    sa.Column('Periodo_Item', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['ReportCard_ID'], ['report_cards.Id'], ),
    sa.ForeignKeyConstraint(['UAC_ID'], ['uacs.Id'], ),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('ReportCard_ID', 'Clave_UAC', 'Semestre', name='uq_rci_rc_clave_sem')
    )
    op.create_index('ix_rci_clave', 'report_card_items', ['Clave_UAC'], unique=False)
    op.create_index('ix_rci_reportcard', 'report_card_items', ['ReportCard_ID'], unique=False)
    op.create_index('ix_rci_semestre', 'report_card_items', ['Semestre'], unique=False)
    # Added as nullable=True to avoid errors when adding to non-empty tables on SQL Server.
    # Backfill existing rows and then create a follow-up migration to set NOT NULL and add any constraints.
    op.add_column('identities', sa.Column('Student_Control_Number', sa.String(length=32), nullable=True))
    op.add_column('identities', sa.Column('CURP', sa.String(length=20), nullable=True))
    op.add_column('identities', sa.Column('Full_Name', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identities', 'Full_Name')
    op.drop_column('identities', 'CURP')
    op.drop_column('identities', 'Student_Control_Number')
    op.drop_index('ix_rci_semestre', table_name='report_card_items')
    op.drop_index('ix_rci_reportcard', table_name='report_card_items')
    op.drop_index('ix_rci_clave', table_name='report_card_items')
    op.drop_table('report_card_items')
    op.drop_index('ix_report_cards_periodo', table_name='report_cards')
    op.drop_index('ix_report_cards_identity_periodo', table_name='report_cards')
    op.drop_table('report_cards')
    op.drop_table('report_card_raw')
    op.drop_table('uacs')
    # ### end Alembic commands ###
