"""updates v2

Revision ID: b5b63fadef32
Revises: a68a7fd643fd
Create Date: 2025-11-30 18:00:43.708507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5b63fadef32'
down_revision: Union[str, Sequence[str], None] = 'a68a7fd643fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_card_items', sa.Column('UAC_ID', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'report_card_items', 'uacs', ['UAC_ID'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_card_items', type_='foreignkey')
    op.drop_column('report_card_items', 'UAC_ID')
    # ### end Alembic commands ###
