"""add missing fields in IM_v5

Revision ID: b79ef02281e0
Revises: df614254f386
Create Date: 2026-01-24 18:08:00.267450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b79ef02281e0'
down_revision: Union[str, Sequence[str], None] = 'df614254f386'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('identities', sa.Column('Midle_Name', sa.String(length=100), nullable=True))
    op.add_column('identities', sa.Column('Last_Name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('identities', 'Last_Name')
    op.drop_column('identities', 'Midle_Name')
    # ### end Alembic commands ###
