"""add content_pages_model

Revision ID: bb88ec10bd93
Revises: e49d3e7f28f6
Create Date: 2026-02-02 21:02:40.377361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb88ec10bd93'
down_revision: Union[str, Sequence[str], None] = 'e49d3e7f28f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_pages',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Description', sa.String(), nullable=True),
    sa.Column('Titule', sa.String(), nullable=True),
    sa.Column('UrlImage', sa.String(), nullable=False),
    sa.Column('Page', sa.String(), nullable=True),
    sa.Column('ComponentPage', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_pages')
    # ### end Alembic commands ###
