"""init schema v3 with idetitys

Revision ID: e11f73912b0b
Revises: 4d5a4e1b47eb
Create Date: 2025-09-24 10:51:59.475899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e11f73912b0b'
down_revision: Union[str, Sequence[str], None] = '4d5a4e1b47eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('identities',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Student_Identity', sa.Integer(), nullable=False),
    sa.Column('Teacher_Identity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id'),
    sa.UniqueConstraint('Student_Identity'),
    sa.UniqueConstraint('Teacher_Identity')
    )
    op.add_column('users', sa.Column('Telephone', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('FK_Identity_ID', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'identities', ['FK_Identity_ID'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'FK_Identity_ID')
    op.drop_column('users', 'Telephone')
    op.drop_table('identities')
    # ### end Alembic commands ###
