"""Update Models

Revision ID: e770f4859e42
Revises: a8a8c0ae0e3e
Create Date: 2025-11-23 19:40:00.435379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e770f4859e42'
down_revision: Union[str, Sequence[str], None] = 'a8a8c0ae0e3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure there are no NULL Student_Control_Number values before making the column NOT NULL.
    # Populate missing values with a deterministic placeholder to preserve uniqueness.
    op.execute(
        """
        UPDATE identities
        SET Student_Control_Number = 'unknown-' + CAST(Id AS VARCHAR(32))
        WHERE Student_Control_Number IS NULL
        """
    )
    op.alter_column('identities', 'Student_Control_Number',
               existing_type=sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'),
               nullable=False)
    op.add_column('report_card_raw', sa.Column('ReportCard_Item_ID', sa.Integer(), nullable=True))
    op.add_column('report_card_raw', sa.Column('UAC_ID', sa.Integer(), nullable=True))
    op.add_column('report_card_raw', sa.Column('Clave_UAC', sa.String(length=32), nullable=True))
    op.add_column('report_card_raw', sa.Column('Semestre', sa.Integer(), nullable=True))
    op.add_column('report_card_raw', sa.Column('Nombre', sa.String(length=200), nullable=True))
    op.add_column('report_card_raw', sa.Column('Calificacion', sa.Numeric(precision=4, scale=2), nullable=True))
    op.add_column('report_card_raw', sa.Column('Periodo_Item', sa.String(length=64), nullable=True))
    op.create_index('ix_rcr_identity_periodo_clave', 'report_card_raw', ['Identity_ID', 'Periodo', 'Clave_UAC'], unique=False)
    op.create_foreign_key(None, 'report_card_raw', 'report_card_items', ['ReportCard_Item_ID'], ['Id'])
    op.create_foreign_key(None, 'report_card_raw', 'uacs', ['UAC_ID'], ['Id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'report_card_raw', type_='foreignkey')
    op.drop_constraint(None, 'report_card_raw', type_='foreignkey')
    op.drop_index('ix_rcr_identity_periodo_clave', table_name='report_card_raw')
    op.drop_column('report_card_raw', 'Periodo_Item')
    op.drop_column('report_card_raw', 'Calificacion')
    op.drop_column('report_card_raw', 'Nombre')
    op.drop_column('report_card_raw', 'Semestre')
    op.drop_column('report_card_raw', 'Clave_UAC')
    op.drop_column('report_card_raw', 'UAC_ID')
    op.drop_column('report_card_raw', 'ReportCard_Item_ID')
    op.alter_column('identities', 'Student_Control_Number',
               existing_type=sa.VARCHAR(length=32, collation='Modern_Spanish_CI_AS'),
               nullable=True)
    # ### end Alembic commands ###
