"""add content_model_v4

Revision ID: f27008736b71
Revises: 44e2b0a3bea0
Create Date: 2026-02-02 20:22:56.201422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f27008736b71'
down_revision: Union[str, Sequence[str], None] = '44e2b0a3bea0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Contents',
    sa.Column('Id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Description', sa.String(), nullable=False),
    sa.Column('Titule', sa.String(), nullable=False),
    sa.Column('Type', sa.String(), nullable=False),
    sa.Column('UrlImage', sa.String(), nullable=False),
    sa.Column('UrlDocument', sa.String(), nullable=False),
    sa.Column('IsAnAdvice', sa.Boolean(), nullable=False),
    sa.Column('CreationDate', sa.Date(), nullable=False),
    sa.Column('EndDate', sa.Date(), nullable=False),
    sa.Column('IsActive', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Contents')
    # ### end Alembic commands ###
